//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resources.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDS_FIRSTDAY                    102
#define IDD_RESOURCES_DIALOG            102
#define IDS_SECONDDAY                   103
#define IDD_DIALOG_SHOWMSG              103
#define IDS_STRING104                   104
#define IDD_REG                         105
#define IDB_BITMAP1                     120
#define IDR_MENU_POPUP                  125
#define IDD_DIALOG_SHEET1               130
#define IDD_DIALOG_SHEET3               136
#define IDD_ADDTERMINAL                 140
#define IDD_HELP                        142
#define IDD_ADMIN                       144
#define IDD_SETCOMNAME                  147
#define IDD_SET                         148
#define IDI_MAINICON                    200
#define IDI_CFGICON                     201
#define IDI_MOUSE_CURSOR                202
#define IDC_COPY                        1000
#define IDC_PURSE                       1001
#define IDC_CPANDPUS                    1002
#define IDC_TAB4                        1006
#define IDC_TABTEST                     1006
#define IDC_JISUANQI                    1007
#define IDC_REGCODE                     1007
#define IDC_MACHCODE                    1008
#define IDC_REG                         1009
#define IDC_EDITF1                      1013
#define IDC_EDITF2                      1014
#define IDC_STATICMACHCODE              1014
#define IDC_EDITF3                      1015
#define IDC_EDITPORT                    1016
#define IDC_EDITF4                      1016
#define IDC_EDITF5                      1017
#define IDC_EDITF6                      1018
#define IDC_DEFAULT                     1019
#define IDC_EDITF7                      1019
#define IDC_EDITF8                      1020
#define IDC_IPADDRESSVALUE              1021
#define IDC_EDITF9                      1021
#define IDC_EDITF10                     1022
#define IDC_EDITF11                     1023
#define IDC_EDITF12                     1024
#define IDC_RADIO1                      1030
#define IDC_RADIO2                      1031
#define IDC_BUTTONBACKGROUND            1032
#define IDC_BUTTONFONT                  1033
#define IDC_RADIO3                      1033
#define IDC_BUTTONEDGEC                 1038
#define IDC_RADIO4                      1040
#define IDC_ZHIFU2                      1055
#define IDC_EDITRIGHT                   1066
#define IDC_EDITDOWN                    1067
#define GRPCONNECTSET                   1080
#define IDC_CHECKDISPLAY                1082
#define IDC_CURSONBLINK                 1083
#define IDC_FONTHEIGHT                  1084
#define IDC_FONTWIDTH                   1086
#define IDC_CURSONR                     1087
#define IDC_CURSONG                     1088
#define IDC_BUTTONCURSON                1089
#define IDC_BACKR                       1090
#define IDC_BACKG                       1091
#define IDC_BACKB                       1092
#define IDC_FONTR                       1093
#define IDC_FONTG                       1094
#define IDC_FONTB                       1095
#define IDC_CURSONB                     1096
#define IDC_EDGER                       1097
#define IDC_EDGEG                       1098
#define IDC_EDGEB                       1099
#define IDC_FILEPATH                    1100
#define IDC_WAVFILE                     1102
#define IDC_TEXTBLINK                   1103
#define IDC_LOGTYPE                     1104
#define IDC_WARNONCLOSE                 1105
#define IDC_AUTOCOPY                    1106
#define IDC_CURSONTYPE0                 1107
#define IDC_CURSONTYPE1                 1108
#define IDC_CURSONTYPE2                 1109
#define IDD_DIALOG_SHEET2               1114
#define IDC_COM5W                       1115
#define IDC_LINECODEPAGE                1116
#define IDD_DIALOG_SHEET4               1116
#define IDC_BROWSE                      1117
#define IDC_RICHEDIT21                  1124
#define IDC_BKSBS                       1125
#define IDC_BKSDEL                      1126
#define IDC_BKSLEFT                     1127
#define IDC_DELETERETURN                1128
#define IDC_DELETEDEL                   1129
#define IDC_LOGINPROMPT                 1130
#define IDC_PASSWORDPROMPT              1131
#define IDC_USERNAME                    1132
#define IDC_PASSWORD                    1133
#define IDC_AUTOLOGIN                   1134
#define IDC_TERMNAME                    1135
#define IDC_SECTIONNAME                 1136
#define IDC_TERMIP                      1137
#define IDC_TERMPORT                    1139
#define IDC_SHORTCUTSPATH               1141
#define IDC_DESCRIPTION                 1142
#define IDC_SELECT                      1143
#define IDC_DESKTOP                     1144
#define IDC_IPADDRESS1                  1146
#define IDC_UPDATEIP                    1146
#define IDC_EDIT1                       1147
#define IDC_UPDATEPORT                  1147
#define IDC_PRINTERNAME                 1147
#define IDC_NEWSCREENNUM                1147
#define IDC_EDITESC                     1147
#define IDC_ECOM1                       1147
#define IDC_EDITEND                     1148
#define IDC_NONUMLOCK                   1149
#define IDC_EDITDELETE                  1151
#define IDC_EDITPAGEDOWN                1152
#define IDC_COMBO1                      1153
#define IDC_PRINTMODE                   1153
#define IDC_EDITHOME                    1153
#define IDC_RETURNPAPER                 1153
#define IDC_BANDY                       1153
#define IDC_PINGINTERVAL                1154
#define IDC_EDITDIV                     1154
#define IDC_BANDZ                       1154
#define IDC_TCPKEEPALIVES               1155
#define IDC_BANDX                       1155
#define IDC_EDITINSERT                  1156
#define IDC_BANDU                       1156
#define IDC_EDITBACKSPACE               1157
#define IDC_BANDW                       1157
#define IDC_ALLOWREPEAT                 1158
#define IDC_EDITMULT                    1158
#define IDC_BANDV                       1158
#define IDC_EDIT2                       1159
#define IDC_SCREENNUM                   1159
#define IDC_ADMINPASSWORD               1159
#define IDC_EDITNUMLOCK                 1159
#define IDC_ECOM2                       1159
#define IDC_ENABLESCREENNUM             1160
#define IDC_EDITSUB                     1160
#define IDC_PRINTSTATIC                 1161
#define IDC_EDITPAGEUP                  1161
#define IDC_STPRINTNAME                 1161
#define IDC_EDITADD                     1162
#define IDC_EDITPRINTSCREEN             1163
#define IDC_EDITPAUSE                   1165
#define IDC_EDITSCROLL                  1166
#define IDC_ALLOWSHORTCUTS              1170
#define IDC_ALLOWFUNCTION               1171
#define IDC_EDITUP                      1172
#define IDC_EDITLEFT                    1173
#define IDC_PRINTCOM                    1175
#define IDC_SYSPASS                     1176
#define IDC_SYSUSER                     1177
#define IDC_SETCOMNAME                  1178
#define IDC_SCOM1Y                      1179
#define IDC_SCOM2Z                      1180
#define IDC_SCOM3X                      1181
#define IDC_SCOM4U                      1182
#define IDC_SCOM5W                      1183
#define IDC_SCOM6V                      1184
#define IDC_COM1Y                       1185
#define IDC_COM2Z                       1186
#define IDC_COM3X                       1187
#define IDC_COM4U                       1188
#define IDC_COM6V                       1189
#define IDC_ECOM3                       1190
#define IDC_ECOM4                       1191
#define IDC_ECOM5                       1192
#define IDC_ECOM6                       1193
#define IDC_RESETNAME                   1194
#define IDC_TAB1                        1195
#define IDC_RESUMVALUE                  1196
#define IDC_APPLICATION                 1197
#define IDC_CURRENTUSER                 1198
#define IDC_CHECK2                      1199
#define IDC_DEBUG                       1199
#define IDC_EPSHARE                     1200
#define IDC_SSHARE                      1201
#define IDC_SPDIR                       1202
#define IDC_USESETY                     1203
#define IDC_BYTEY                       1204
#define IDC_STOPY                       1205
#define IDC_PARIYY                      1206
#define IDC_USESETZ                     1207
#define IDC_BYTEZ                       1208
#define IDC_STOPZ                       1209
#define IDC_PARIYZ                      1210
#define IDC_USESETX                     1211
#define IDC_BYTEX                       1212
#define IDC_STOPX                       1213
#define IDC_PARIYX                      1214
#define IDC_USESETU                     1215
#define IDC_BYTEU                       1216
#define IDC_STOPU                       1217
#define IDC_PARIYU                      1218
#define IDC_USESETW                     1219
#define IDC_BYTEW                       1220
#define IDC_STOPW                       1221
#define IDC_PARIYW                      1222
#define IDC_USESETV                     1223
#define IDC_BYTEV                       1224
#define IDC_STOPV                       1225
#define IDC_COMBO24                     1226
#define IDC_PARIYV                      1226
#define IDM_INCREMENT                   32772
#define IDM_TEST                        32773
#define ID_Menu                         32774
#define IDM_INACTIVE                    32775
#define ID_32776                        32776
#define ID_                             32777
#define ID_DESCRIPTION                  32778
#define IDM_DESCRIPTION                 32779
#define IDM_COPY                        40010
#define IDM_PASTE                       40011
#define IDM_ABOUTME                     40017
#define IDM_CAL                         40019
#define IDM_NEWTELNET                   40020
#define IDM_RESTARTTELNET               40021
#define IDM_ALLSCREENSHOW               40022
#define IDM_ZXH                         40030
#define IDM_EXIT_SYSTEM                 40032
#define IDM_COPY_SCREEN                 40033
#define IDM_CONNECTION                  40034
#define IDM_INTERFACE                   40035
#define IDM_SHOW                        40036
#define IDM_USERKEY                     40037
#define IDM_OTHER                       40038
#define IDM_HELPDOC                     40042
#define ID_40047                        40047
#define ID_40048                        40048
#define ID_40049                        40049
#define ID_40050                        40050
#define IDM_COPY_PASTE                  40053
#define IDM_PRINT_SCREEN                41019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1207
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
