TARGET = terminal.exe
LDFLAGS = -mwindows -static
INC_PATH = ../include /c/MinGW/mingw32/include
LIBS_PATH = ../libs
LIBS_NAME = IPHLPAPI wsock32 WinIo winmm mapi32 imm32 winspool comctl32 comdlg32 gdi32 ole32 user32 uuid getPcMsgApi wininet
SRC_PATH = ../util util  windows .
C_PATH = $(SRC_PATH)
CPP_PATH = $(SRC_PATH) 
RESOURCES = resources/resources.o

#DEBUG=true
include ../include.mk
